apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
  namespace: eshop
  labels:
    app: keycloak
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
        - name: keycloak
          image: quay.io/keycloak/keycloak:24.0.3
          args:
            - "start"  # Run in production mode
            - --hostname=staging.keycloak.iprovler.com
            #- --http-enabled=true                     # ⚠️ Only for testing — remove in prod!
            - --hostname-strict=false                 # Loosen hostname rules
            - --hostname-strict-https=false           # Allow HTTP instead of HTTPS
            - --proxy=edge                            # If behind ingress or reverse proxy
          ports:
            - containerPort: 8080
            - containerPort: 8443
          env:
            - name: KEYCLOAK_ADMIN
              value: "admin"
            - name: KEYCLOAK_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: keycloak-admin-password  # A secret for better security
                  key: password
            - name: DB_VENDOR
              value: "postgres"
            - name: DB_ADDR
              value: "keycloak-db"  # The name of the PostgreSQL service
            - name: DB_DATABASE
              value: "keycloak"
            - name: DB_USER
              value: "keycloakuser"
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: keycloak-db-password  # Secret to store DB password
                  key: password
            - name: KEYCLOAK_HTTP_PORT
              value: "8080"
          volumeMounts:
            - name: keycloak-logs
              mountPath: /opt/keycloak/logs  # Mounting logs for persistence
            - name: tls-certs
              mountPath: /etc/x509/https
              readOnly: true
      volumes:
        - name: keycloak-logs
          emptyDir: {}  # Change this to persistent volume if you need durable logs
        - name: tls-certs
          secret:
            secretName: keycloak-tls-gf8wh 
---
apiVersion: v1
kind: Secret
metadata:
  name: keycloak-admin-password
  namespace: eshop
type: Opaque
data:
  password: a2V5Q2wwYWtQQHNzIQ==  # Base64-encoded admin password
